Add benchmarks.
Remove generated files.

First buildconf complete.

Start httpperf library conf fixes.

httperf-0.9.0 and references. Possibly a fork, but no release since 2007

Forgot httperf/man

Initial Add: Iozone3, under evaluation regarding Open Source licensing problems.

Run shell updates.

Benchmark Build modifications

Add Yocto recipes-benchmarks to get in sync, and modify with current benchmark versions where applicable.

First Add: Bonnie to Autotools.

New template run.sh. Simulator options for all scripts.

Ported 11 cross compilers.

First add: Memtester

Add lttng. Generic Autotools for iozone3 and memtester.

Mods for Ubuntu 10.04 autotools.

First distcheck

First Add Tiobench 0.4.1

Merge Ubuntu porting.

Benchmark Adds.

Add all Open Source Benchmarks (Latest Versions)

diff --git a/dhrystone/dhrystone-run.sh.in b/dhrystone/dhrystone-run.sh.in
--- a/dhrystone/dhrystone-run.sh.in
+++ b/dhrystone/dhrystone-run.sh.in
@@ -1,53 +1,79 @@
-#!/bin/sh
-## Run script for dhrystone 2.1
+#!/bin/bash
+## Run script for dhrystone.
 # @author Rick Foos
 # @file
 
+#debug
+set -x #echo onset +x #echo off
+
+# Simple optarg to set environment variables, and execute commands.
 for i
 do
-	valid=`echo $i | sed -e "s|[^=]||g"`
-	if [ -n "$valid" ]
-	then
-		eval $i
-		#echo $i
-	else
-		echo "INFO: Invalid argument $i"
-	fi
+    validopt=$(sed -e "s|[^=]||g" <<<$i)
+    if [ -n "$validopt" ]
+    then
+        eval $i
+        echo "INFO: Option  $i"
+        ## Use this block for fixed option set.
+        #opt=$(sed -e "s|\([^=]*\).*|\1|" <<<$i)
+        #case $opt in
+        #srcdir | bindir)
+        #    eval $i
+        #    echo "INFO: Option  $i";;
+        #*)      echo "WARNING: Invalidopt option: $option";;
+        #esac
+    else
+        echo "WARNING: Invalid command $i ignored"
+        ## Use this block for fixed command set.
+        #echo "INFO: Command  $i"
+        #case $i in
+        #shortrun)
+        #    cmd_SHORTRUN="YES"
+        #    ;;
+        #clean)
+        #    cmd_CLEAN="YES"
+        #    ;;
+        #*)      echo "WARNING: Invalid command $i ignored";;
+        #esac
+    fi
 done
-## Optional Simulator run.
-EXEC="@SIM@"
 
-[ -z "$srcdir" ] && srcdir=.
-[ -z "$bindir" ] && bindir=.
-[ -z "$run_PROG" ] && run_PROG=${bindir}/dhrystone
-[ -z "$run_OUT" ] && run_OUT=${srcdir}/dhrystone.txt
-# Tune for your system.
-[ -z "$run_LOOPS" ] && run_LOOPS=9000000
+## Allows Simulator or other exec tools.
+[ -n ${SIMULATOR} ] || SIMULATOR="@SIMULATOR@"
+[ -n "${srcdir}" ] || srcdir="$(dirname $0)" # srcdir: @srcdir@
+[ -n "${bindir}" ] || bindir="$(dirname $0)" # bindir: @bindir@
+[ -n "${PROGRAM}" ] || PROGRAM="${bindir}/dhrystone"
+[ -n "${OUTFILE}" ] || OUTFILE="${srcdir}/dhrystone.txt"
+#[ -n "${ARGS}" ] || ARGS=""
 
+## @note Must adjust LOOPS for your system, error if time captured invalid.
+[ -n "${LOOPS}" ] || LOOPS=9200000
 
-# Check executables
+# Command Execution
+[ "${RUNCMD}" == "clean" ] && rm -f ${OUTFILE} && echo "INFO: clean..."
 
-if [ ! -x "${run_PROG}" ] 
+# Check executable
+if [ ! -x "${PROGRAM}" ]
 then
-	echo "ERROR: ${run_PROG} not found or not executable"
-	exit 1
+    echo "ERROR: ${PROGRAM} not found or not executable"
+    exit 1
 fi
 
-if [ -f "${run_OUT}" ]
+if [ -f "${OUTFILE}" ]
 then
-	echo "INFO: RERUN results in ${run_OUT}"
+    echo "INFO: RERUN results in ${OUTFILE}"
 else
-	echo "INFO: running ${run_PROG} for ${run_LOOPS} loops..."
-	echo "${run_LOOPS}" | $EXEC ${run_PROG} >${run_OUT}
-        rc=$?
-        if [ "rc" != "0" ]
-        then
-          echo "ERROR: run failed: $rc"
-          rm -f ${run_OUT}
-	elif [ ! -z "`grep increase ${run_OUT}`" ]
-	then
-		echo "ERROR: increase loops (run.sh run_ARGS=xxx)"
-		rm -f ${run_OUT}
-	fi
+    echo "INFO: running ${PROGRAM} for ${LOOPS} loops..."
+    echo "${LOOPS}" | $SIMULATOR ${PROGRAM} ${ARGS} >${OUTFILE}
+    rc=$?
+    if [ "$rc" != "0" ]
+    then
+        echo "ERROR: run failed: $rc"
+        rm -f ${OUTFILE}
+    elif [ -n "$(grep increase ${OUTFILE})" ] # Look for error message
+    then
+        echo "ERROR: increase loops (dhrystone-run.sh LOOPS=xxx)"
+        rm -f ${OUTFILE}
+    fi
 fi
 
diff --git a/postmark/postmark-run.sh.in b/postmark/postmark-run.sh.in
--- a/postmark/postmark-run.sh.in
+++ b/postmark/postmark-run.sh.in
@@ -1,22 +1,67 @@
 #!/bin/bash
+## Postmark Execution
+# @author Rick Foos
+# @file
 
-[ -n "${srcdir}" ] || srcdir=$(pwd)
-[ -n "${bindir}" ] || bindir=$(pwd)
-run_PROG=${bindir}/postmark
-run_OUT=${srcdir}/postmark.txt
-run_IN=${srcdir}/postmark-cmds.txt
+#debug
+set -x #echo onset +x #echo off
 
-if [ ! -x "${run_PROG}" ]
+# Simple optarg to set environment variables, and execute commands.
+for i
+do
+    validopt=$(sed -e "s|[^=]||g" <<<$i)
+    if [ -n "$validopt" ]
+    then
+        eval $i
+        echo "INFO: Option  $i"
+        ## Use this block for fixed option set.
+        #opt=$(sed -e "s|\([^=]*\).*|\1|" <<<$i)
+        #case $opt in
+        #srcdir | bindir)
+        #    eval $i
+        #    echo "INFO: Option  $i";;
+        #*)      echo "WARNING: Invalidopt option: $option";;
+        #esac
+    else
+        echo "WARNING: Invalid command $i ignored"
+        ## Use this block for fixed command set.
+        #echo "INFO: Command  $i"
+        #case $i in
+        #shortrun)
+        #    cmd_SHORTRUN="YES"
+        #    ;;
+        #clean)
+        #    cmd_CLEAN="YES"
+        #    ;;
+        #*)      echo "WARNING: Invalid command $i ignored";;
+        #esac
+    fi
+done
+
+# Set Default values from Autotools, may be overridden in command line
+[ -n "${srcdir}" ] || srcdir=$(dirname $0) # srcdir: @srcdir@
+[ -n "${bindir}" ] || bindir=$(dirname $0) # bindir: @bindir@
+[ -n "${SIMULATOR}" ] || SIMULATOR=@SIMULATOR@
+[ -n "${PROGRAM}" ] || PROGRAM="$bindir/postmark"
+[ -n "${OUTFILE}" ] || OUTFILE="${srcdir}/postmark.txt"
+#[ -n "${ARGS}" ] || ARGS=""
+[ -n "${INFILE}" ] || INFILE=${srcdir}/postmark-cmds.txt
+
+# Command Execution
+[ "${RUNCMD}" == "clean" ] && rm -f ${OUTFILE} && echo "INFO: clean..."
+
+# Check executable
+if [ ! -x "${PROGRAM}" ]
 then
-	echo "ERROR: ${run_PROG} not found or not executable"
-	exit 1
+    echo "ERROR: ${PROGRAM} not found or not executable"
+    exit 1
 fi
 
-if [ -f "${run_OUT}" ]
+if [ -f "${OUTFILE}" ]
 then
-	echo "INFO: skipping, results in ${run_OUT}"
+	echo "INFO: skipping, results in ${OUTFILE}"
 else
-	echo "INFO: running ${run_PROG} ..."
-	${run_PROG} <${run_IN} >${run_OUT}
+	echo "INFO: running ${PROGRAM} ..."
+	${SIMULATOR} ${PROGRAM} ${ARGS} <${INFILE} >${OUTFILE}
 fi
 
